import { createClient, createServiceClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { card_id } = await req.json() as { card_id: string }
    if (!card_id) return NextResponse.json({ error: 'card_id required' }, { status: 400 })

    const service = createServiceClient()

    const { data: subscriber } = await service
      .from('subscribers')
      .select('id')
      .eq('user_id', user.id)
      .single()
    if (!subscriber) return NextResponse.json({ error: 'Subscriber not found' }, { status: 403 })

    // Confirm card belongs to this subscriber
    const { data: card } = await service
      .from('cards')
      .select('id')
      .eq('id', card_id)
      .eq('subscriber_id', subscriber.id)
      .single()
    if (!card) return NextResponse.json({ error: 'Card not found' }, { status: 404 })

    // Deactivate all existing tokens for this card
    await service
      .from('card_holder_tokens')
      .update({ is_active: false })
      .eq('card_id', card_id)
      .eq('is_active', true)

    // Create new token (token value auto-generated by DB default)
    const { data: tokenRow, error: insertErr } = await service
      .from('card_holder_tokens')
      .insert({ card_id, subscriber_id: subscriber.id })
      .select('token')
      .single()

    if (insertErr) return NextResponse.json({ error: insertErr.message }, { status: 500 })

    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? ''
    return NextResponse.json({
      token: tokenRow.token,
      url: `${appUrl}/my-leads/${tokenRow.token}`,
    })
  } catch (e: unknown) {
    return NextResponse.json({ error: e instanceof Error ? e.message : String(e) }, { status: 500 })
  }
}
